name: Tests

on:
    workflow_dispatch: # Only enable manual runs for now

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # Define the Python versions to test against
                python-version: [ "3.10", "3.11", "3.12", "3.13" ]

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set Up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}

            # Install dependencies
            -   name: Install Poetry and Dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install make
                    make setup
                    make install

            # Run unit tests with coverage
            -   name: Run Tests with Coverage
                run: |
                    make test
                    make coverage
                continue-on-error: true

            -   name: Upload Test Results and Coverage Reports
                uses: actions/upload-artifact@v4
                with:
                    name: test-results-and-coverage
                    overwrite: true # Overwrite the existing artifact(s) with the same name
                    path: |
                        junit/test-results-${{ matrix.python-version }}.xml
                        htmlcov-${{ matrix.python-version }}/
